# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On Mac OS X:
#   sudo gem install mysql -- --with-mysql-dir=/usr/local/mysql
# On Mac OS X Leopard:
#   sudo env ARCHFLAGS="-arch i386" gem install mysql -- --with-mysql-config=/usr/local/mysql/bin/mysql_config
#       This sets the ARCHFLAGS environment variable to your native architecture
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql
  database: topfind_development
  username: topfind
  password: t6o0p-
  socket: /var/mysql/mysql.sock



production:
  adapter: mysql
  database: topfind_production
  username: topfind
  password: t6o0p-
  socket: /var/mysql/mysql.sock
  
meropsweb93:
  adapter: mysql
  database: topfind_meropsweb
  username: topfind
  password: t6o0p-
  socket: /var/mysql/mysql.sock


go:
  adapter: mysql
  database: topfind_go
  username: topfind
  password: t6o0p-
  socket: /var/mysql/mysql.sock
  
#local
development:
  adapter: mysql
  database: topfind_development
  pool: 5
  username: root
  password: root
  host: localhost
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

production:
  adapter: mysql
  database: topfind_production
  pool: 5
  username: root
  password: root
  host: localhost
  socket: /Applications/MAMP/tmp/mysql/mysql.sock
  
meropsweb93:
  adapter: mysql
  database: topfind_meropsweb
  pool: 5
  username: root
  password: root
  host: localhost
  socket: /Applications/MAMP/tmp/mysql/mysql.sock


go:
  adapter: mysql
  database: topfind_go
  pool: 5
  username: root
  password: root
  host: localhost
  socket: /Applications/MAMP/tmp/mysql/mysql.sock 
